name: Build & Test

on: [push]

jobs:
  run-tests:
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'
          include-prerelease: true

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget

      - name: Test
        if: ${{ !cancelled() }}
        id: testAction3a
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: Tests
          report_name: tests_xunit-${{ matrix.os }}
          report_title: E2E Test (${{ matrix.os }})
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: dotnet-tests-report_xunit-${{ matrix.os }}.md
          gist_badge_label: 'XUnit Tests: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}
          set_check_status_from_test_outcome: true
          fail_build_on_failed_tests: true
      
      - name: Log
        run: |
          echo 'Testing on: ${{ matrix.os }}'
          echo '  xUnit:'
          echo '    * result_value    = ${{ steps.testAction3a.outputs.result_value }}'
          echo '    * total_count     = ${{ steps.testAction3a.outputs.total_count }}'
          echo '    * passed_count    = ${{ steps.testAction3a.outputs.passed_count }}'
          echo '    * failed_count    = ${{ steps.testAction3a.outputs.failed_count }}'
          echo '    * gist_report_url = ${{ steps.testAction3a.outputs.gist_report_url }}'
          echo '    * gist_badge_url  = ${{ steps.testAction3a.outputs.gist_badge_url }}'
          echo ''
